#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/giaok-keyboard/active-main-user-test"

if [[ -f "$STATE_FILE" ]]; then
    # Generated by install-main-user-test.sh; lets the copied launcher locate
    # the project-local runtime without hard-coding one developer home path.
    project_root=""
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    PROJECT_ROOT="$project_root"
else
    PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi
PREFIX="$PROJECT_ROOT/.local-env/prefix"
SYSROOT_LIB="$PROJECT_ROOT/.local-env/sysroot/usr/lib/x86_64-linux-gnu"

if [[ ! -x "$PREFIX/bin/fcitx5" ]]; then
    echo "Fcitx5 5.1.22 is not built at $PREFIX" >&2
    exit 1
fi

# The 5.1.22 core and patched Rime addon are project-local. System UI and
# frontend addons are reused after the install script checks their ABI.
export LD_LIBRARY_PATH="$PREFIX/lib:$SYSROOT_LIB${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="$PREFIX/share:/usr/local/share:/usr/share"

exec "$PREFIX/bin/fcitx5" --enable rime "$@"
